module.exports = {
  cash: 1000000,
  stockPrices: [
    {
      name: "Aether Dynamics",
      price: 620,
      sector: "Aerospace and Defense",
      totalStock: 60000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [620],
      risk: "upper high end"
    },
    {
      name: "Synapse AI",
      price: 310,
      sector: "Artificial Intelligence",
      totalStock: 32000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [310],
      risk: "high"
    },
    {
      name: "CoreX Systems",
      price: 140,
      sector: "Technology",
      totalStock: 18000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [140],
      risk: "very high"
    },
    {
      name: "Voltaris Energy",
      price: 950,
      sector: "Renewable Energy",
      totalStock: 75000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [950],
      risk: "low"
    },
    {
      name: "Bharat PetroEnergy",
      price: 680,
      sector: "Oil and Gas",
      totalStock: 40000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [680],
      risk: "medium"
    },
    {
      name: "AxisPoint Capital",
      price: 780,
      sector: "Financial Services",
      totalStock: 65000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [780],
      risk: "low"
    },
    {
      name: "Merchant Brothers",
      price: 1150,
      sector: "Consumer Goods",
      totalStock: 28000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [1150],
      risk: "medium-high"
    },
    {
      name: "Dr. Saha's Pharma",
      price: 250,
      sector: "Pharmaceuticals",
      totalStock: 50000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [250],
      risk: "low"
    },
    {
      name: "Helix Biotech",
      price: 410,
      sector: "Biotechnology",
      totalStock: 20000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [410],
      risk: "very high"
    },
    {
      name: "PureLife Industries",
      price: 270,
      sector: "Consumer Staples",
      totalStock: 70000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [270],
      risk: "low"
    },
    {
      name: "UrbanNest Foods",
      price: 195,
      sector: "Food and Beverages",
      totalStock: 35000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [195],
      risk: "medium-high"
    },
    {
      name: "Ahuja Estates",
      price: 980,
      sector: "Real Estate",
      totalStock: 24000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [980],
      risk: "high"
    },
    {
      name: "TitanGrid Infrastructure",
      price: 510,
      sector: "Infrastructure",
      totalStock: 55000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [510],
      risk: "medium-low"
    },
    {
      name: "Awasthi Motors",
      price: 720,
      sector: "Automotive",
      totalStock: 48000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [720],
      risk: "medium"
    },
    {
      name: "Velocity Electric",
      price: 1850,
      sector: "Electric Vehicles",
      totalStock: 15000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [1850],
      risk: "very high"
    },
    {
      name: "Bhatia Aerospace & Defense",
      price: 195,
      sector: "Aerospace and Defense",
      totalStock: 8000,
      stocksBought: 0,
      lastBoughtBy: "",
      lastBoughtPrice: 0,
      lastBoughtQty: 0,
      stockPriceHistory: [195],
      risk: "extreme"
    }
  ]
};