module.exports = {
  cash: 1000000,
  stockprices: [
  {
    "name": "Jameson Appliances",
    "price": 500,
    "sector": "Technology and Innovation",
    "totalStock": 60000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[500],
    "risk":"upper high end"
  },
  {
    "name": "REnergy",
    "price": 150,
    "sector": "Power",
    "totalStock": 25000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[150],
    "risk":"low to medium"
  },
  {
    "name": "TrustBank",
    "price": 750,
    "sector": "Banking and Financial Services",
    "totalStock": 45000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[750],
    "risk":"medium to lower high"
  },
  {
    "name": "Chaudhary and Sons Pharmaceuticals",
    "price": 250,
    "sector": "Pharmaceutical and Healthcare",
    "totalStock": 20000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[250],
    "risk":"low"
  },
  {
    "name": "EverPure FMCG",
    "price": 270,
    "sector": "FMCG",
    "totalStock": 50000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[270],
    "risk":"medium"
  },
  {
    "name": "Velocity",
    "price": 1800,
    "sector": "Aviation",
    "totalStock": 15000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[1800],
    "risk":"mid high to upper high"
  },
  {
    "name": "Farmstead Features",
    "price": 450,
    "sector": "Agriculture",
    "totalStock": 20000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[450],
    "risk":"low during season, high during non season"
  },
  {
    "name": "MetroBuild",
    "price": 950,
    "sector": "Infrastructure",
    "totalStock": 25000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[950],
    "risk":"medium"
  },
  {
    "name": "EZ Business",
    "price": 330,
    "sector": "E-commerce",
    "totalStock": 50000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[330],
    "risk":"high"
  },
  {
    "name": "FinEdge",
    "price": 1100,
    "sector": "Private Equity, Asset Management and Online Investment Services",
    "totalStock": 30000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[1100],
    "risk":"depends on current market conditions"
  },
  {
    "name": "Bhatia Motors",
    "price": 700,
    "sector": "Automobiles",
    "totalStock": 25000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[700],
    "risk":"low"
  },
  {
    "name": "BB Builders",
    "price": 510,
    "sector": "Real Estate",
    "totalStock": 20000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[510],
    "risk":"medium-high"
  },
  {
    "name": "Lalwani BrewWorks",
    "price": 1200,
    "sector": "Alcohol",
    "totalStock": 12000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[1200],
    "risk":"high"
  },
  {
    "name": "Kanishq Jewellers",
    "price": 480,
    "sector": "Diamond and Jewellery",
    "totalStock": 15000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[480],
    "risk":"low"
  },
  {
    "name": "Wagle Global Oils",
    "price": 700,
    "sector": "Oils and Gases",
    "totalStock": 28000,
    "stocksbought":0,
    "lastBoughtBy":"",
    "lastBoughtPrice":0,
    "lastBoughtQty":0,
    "stockPriceHistory":[700],
    "risk":"medium"
  }
]
};